storage_folder_path: "./storage" # Root folder for all the storage stuff
user_data_path: "/user_data"
proof_path: "/proof"
public_inputs_path: "/public_inputs"
reduced_proof_path: "/reduced_proof"
reduced_pis_path: "/reduced_pis"
reduced_circuit_path: "/reduced_circuit"
imt_circuit_data_path: "/imt_circuit"
aggregated_circuit_data: "./aggregated_circuit_data"
supperproof_path: "/superproofs"
verification_contract_address: "0x61fd0575f92837057f571fc949b449b865fcdb09"
imt_depth: 10
batch_size: 10 # Number of proofs to be included in 1 batch
worker_sleep_secs: 10
