storage_folder_path: "./storage" # Root folder for all the storage stuff
user_data_path: "/user_data"
proof_path: "/proof"
public_inputs_path: "/public_inputs"
reduced_proof_path: "/reduced_proof"
reduced_pis_path: "/reduced_pis"
reduced_circuit_path: "/reduced_circuit"
imt_circuit_data_path: "/imt_circuit"
aggregated_circuit_data: "./aggregated_circuit_data"
supperproof_path: "/superproofs"
verification_contract_address: "0x6afbB1c4296D2b4d333E24f2462b15f2D97449Cb"
imt_depth: 10
max_batch_size: 32 # Number of proofs to be included in 1 batch
worker_sleep_secs: 10
reduced_proof_receipt_path: /receipt
aggregation_wait_time: 720
risc0_snark_reduction_data_path: /risc0_snark_reduction
sp1_snark_reduction_data_path: /sp1_snark_reduction
parallel_bonsai_session_limit: 5
sp1_empty_proof_path: /sp1_empty_proof.bin
pr_batch_max_cycle_count: 3400000000
# sp1_agg_pkey_path: /