[development]
address = "0.0.0.0"
port = 8000

[global]
address = "0.0.0.0"
port = 8000
cli_colors = false

[production]
address = "0.0.0.0"
port = 8000

[default.limits]
json = "10 MiB"
# "application/json" = "100 MiB"
data = "10 MiB"
# msgpack = "100 MiB"
bytes = "10 MiB"
# form = "100 MiB"
# "file/jpg" = "100 MiB"
string = "10 MiB"
